export const PAYS = [
"Afghanistan",
"Afrique du Sud",
"Albanie",
"Algérie",
"Allemagne",
"Ancienne République yougoslave de Macédoine",
"Andorre",
"Angola",
"Anguilla",
"Antarctique",
"Antigua-et-Barbuda",
"Antilles néerlandaises",
"Arabie saoudite",
"Argentine",
"Arménie",
"Aruba",
"Australie",
"Autriche",
"Azerbaïdjan",
"Bahamas",
"Bahreïn",
"Bangladesh",
"Barbade",
"Belgique",
"Belize",
"Bénin",
"Bermudes",
"Bhoutan",
"Biélorussie",
"Bolivie",
"Bosnie-et-Herzégovine",
"Botswana",
"Brésil",
"Brunei Darussalam",
"Bulgarie",
"Burkina Faso",
"Burundi",
"Cambodge",
"Cameroun",
"Canada",
"Cap-Vert",
"Chili",
"Chine",
"Chypre",
"Colombie",
"Comores",
"Congo",
"Costa Rica",
"Côte d'Ivoire",
"Croatie",
"Cuba",
"Danemark",
"Djibouti",
"Dominique",
"Égypte",
"El Salvador",
"Émirats arabes unis",
"Équateur",
"Érythrée",
"Espagne",
"Estonie",
"États fédérés de Micronésie",
"États-Unis",
"Éthiopie",
"Fidji",
"Finlande",
"France",
"Gabon",
"Gambie",
"Géorgie",
"Géorgie du Sud-et-les Îles Sandwich du Sud",
"Ghana",
"Gibraltar",
"Grèce",
"Grenade",
"Groenland",
"Guadeloupe",
"Guam",
"Guatemala",
"Guinée",
"Guinée équatoriale",
"Guinée-Bissau",
"Guyane",
"Guyane française",
"Haïti",
"Honduras",
"Hong Kong",
"Hongrie",
"Ile Bouvet",
"Ile Christmas",
"Île Norfolk",
"Île Pitcairn",
"Iles Aland",
"Iles Cayman",
"Iles Cocos (Keeling)",
"Iles Cook",
"Îles Féroé",
"Îles Heard-et-MacDonald",
"Îles Malouines",
"Îles Mariannes du Nord",
"Îles Marshall",
"Îles mineures éloignées des États-Unis",
"Îles Salomon",
"Îles Turques-et-Caïques",
"Îles Vierges britanniques",
"Îles Vierges des États-Unis",
"Inde",
"Indonésie",
"Iraq",
"Irlande",
"Islande",
"Israël",
"Italie",
"Jamahiriya arabe libyenne",
"Jamaïque",
"Japon",
"Jordanie",
"Kazakhstan",
"Kenya",
"Kirghizistan",
"Kiribati",
"Koweït",
"Lesotho",
"Lettonie",
"Liban",
"Libéria",
"Liechtenstein",
"Lituanie",
"Luxembourg",
"Macao",
"Madagascar",
"Malaisie",
"Malawi",
"Maldives",
"Mali",
"Malte",
"Maroc",
"Martinique",
"Maurice",
"Mauritanie",
"Mayotte",
"Mexique",
"Monaco",
"Mongolie",
"Montserrat",
"Mozambique",
"Myanmar",
"Namibie",
"Nauru",
"Népal",
"Nicaragua",
"Niger",
"Nigéria",
"Niué",
"Norvège",
"Nouvelle-Calédonie",
"Nouvelle-Zélande",
"Oman",
"Ouganda",
"Ouzbékistan",
"Pakistan",
"Palaos",
"Panama",
"Papouasie-Nouvelle-Guinée",
"Paraguay",
"Pays-Bas",
"Pérou",
"Philippines",
"Pologne",
"Polynésie française",
"Porto Rico",
"Portugal",
"Province chinoise de Taiwan",
"Qatar",
"République arabe syrienne",
"République centrafricaine",
"République de Corée",
"République de Moldavie",
"République démocratique du Congo",
"République dominicaine",
"République islamique d'Iran",
"République populaire démocratique de Corée",
"République Populaire du Laos",
"République tchèque",
"République-Unie de Tanzanie",
"Réunion",
"Roumanie",
"Royaume-Uni",
"Russie",
"Rwanda",
"Sahara occidental",
"Saint-Christophe-et-Niévès",
"Saint-Marin",
"Saint-Pierre-et-Miquelon",
"Saint-Siège (Cité du Vatican)",
"Saint-Vincent-et-les Grenadines",
"Sainte-Hélène",
"Sainte-Lucie",
"Samoa",
"Samoa américaines",
"Sao Tomé-et-Principe",
"Sénégal",
"Serbie-et-Monténégro",
"Seychelles",
"Sierra Leone",
"Singapour",
"Slovaquie",
"Slovénie",
"Somalie",
"Soudan",
"Sri Lanka",
"Suède",
"Suisse",
"Suriname",
"Svalbard et Jan Mayen",
"Swaziland",
"Tadjikistan",
"Tchad",
"Territoire britannique de l'océan Indien",
"Territoire Francais du Sud",
"Territoires palestiniens occupés",
"Thaïlande",
"Timor oriental",
"Togo",
"Tokelau",
"Tonga",
"Trinité-et-Tobago",
"Tunisie",
"Turkménistan",
"Turquie",
"Tuvalu",
"Ukraine",
"Uruguay",
"Vanuatu",
"Vénézuéla",
"Vietnam",
"Wallis-et-Futuna",
"Yémen",
"Zambie",
"Zimbabwe",
] 